Areas/Admin/Controllers/DonHangController.cs
using ShopOnline.Context;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopOnline.Areas.Admin.Controllers
{
    public class DonHangController : Controller
    {
        ShopOnlineEntities objShopOnlineEntities = new ShopOnlineEntities();
        // GET: Admin/DonHang
        public ActionResult Index()
        {
            var lstDonHang = objShopOnlineEntities.ThanhToans.ToList();
            return View(lstDonHang);
            
        }

        [HttpGet]
        public ActionResult Create()
        {

            return View();
        }


        [HttpPost]
        public ActionResult Create(ThanhToan loaisp)
        {
            //Load dropdownlist nhà cung cấp và dropdownlist loại sp, mã nhà sx
            objShopOnlineEntities.ThanhToans.Add(loaisp);
            objShopOnlineEntities.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var loaisp = objShopOnlineEntities.ThanhToans.Where(n => n.id == id).FirstOrDefault();
            return View(loaisp);
        }


        [HttpPost]
        public ActionResult Edit(int id, ThanhToan loaisp)
        {
            objShopOnlineEntities.Entry(loaisp).State = EntityState.Modified;
            objShopOnlineEntities.SaveChanges();
            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult Delete(int id)
        {
            var loaisp = objShopOnlineEntities.ThanhToans.Where(n => n.id == id).FirstOrDefault();
            return View(loaisp);
        }


        [HttpPost]
        public ActionResult Delete(int id, ThanhToan objDelete)
        {
            var loaisp = objShopOnlineEntities.ThanhToans.Where(n => n.id == id).FirstOrDefault();
            objShopOnlineEntities.ThanhToans.Remove(loaisp);
            objShopOnlineEntities.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Detais(int id)
        {
            var loaisp = objShopOnlineEntities.ThanhToans.Where(n => n.id == id).FirstOrDefault();
            return View(loaisp);
        }
    }
}

Areas/Admin/Views/DonHang/Delete.cshtml
@model ShopOnline.Context.ThanhToan

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2 style="text-align:center">Delete</h2>

<h3 style="text-align:center">Are you sure you want to delete this?</h3>
<div>
    <a href="@Url.Action("Index", "DonHang")" class="nav-link active" style="text-align:center">Thanh Toán</a>
    <hr />
    <dl style="width:70%;margin:auto;" class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayTao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayTao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.FirstName)
        </dd>

    </dl>

    @using (Html.BeginForm("Delete", "DonHang", FormMethod.Post, new { @style = "width:50%;margin:auto;", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index", "DonHang")
        </div>
    }
</div>

Areas/Admin/Views/DonHang/Index.cshtml
@model List<ShopOnline.Context.ThanhToan>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<head>
    <style>
        table {
            border-collapse: collapse;
            width: 85%;
            margin: auto;
        }

        th, td {
            text-align: left;
            padding: 5px;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
    </style>
</head>

<body>

    <h2 style="text-align:center">Quản Lý Đơn Hàng </h2>
    <p style="text-align:center"> @Html.ActionLink("Create", "Create", "DonHang")</p>


    <div style="overflow-x:auto;">
        <table>
            <tr>
                <th>Họ Tên</th>
                <th>User ID</th>
                <th>Số điện thoại</th>
                <th>Ngày Tạo </th>
                <th>Email</th>
                <th>Địa Chỉ</th>
            </tr>
            @foreach(var item in Model)
            {
        <tr>
            <td>@item.Name</td>
            <td>@item.UserID</td>
            <td>@item.Status</td>
            <td>@item.NgayTao</td>
            <td>@item.Email</td>
            <td>@item.DiaChi</td>
            <td>
                <a href="@Url.Action("Edit", "DonHang", new { id = item.id })" class="nav-link active">Edit</a>
                <a href="@Url.Action("Detais", "DonHang", new { id = item.id })" class="nav-link active">Detais</a>
                <a href="@Url.Action("Delete", "DonHang", new { id = item.id })" class="nav-link active">Delete</a>

            </td>
        </tr>
            }


        </table>
    </div>

</body>