Areas/Admin/Controllers/LoaiSPController.cs
using ShopOnline.Context;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopOnline.Areas.Admin.Controllers
{
    public class LoaiSPController : Controller
    {

        ShopOnlineEntities objShopOnlineEntities = new ShopOnlineEntities();
        // GET: Admin/LoaiSP
        public ActionResult LoaiSP()
        {
            var lstLoaiSP = objShopOnlineEntities.LoaiSanPhams.ToList();
            return View(lstLoaiSP);
        }

        [HttpGet]
        public ActionResult Create()
        {

            return View();
        }


        [HttpPost]
        public ActionResult Create(LoaiSanPham loaisp)
        {
            //Load dropdownlist nhà cung cấp và dropdownlist loại sp, mã nhà sx
            objShopOnlineEntities.LoaiSanPhams.Add(loaisp);
            objShopOnlineEntities.SaveChanges();
            return RedirectToAction("LoaiSP");
        }


        [HttpGet]
        public ActionResult Edit(string id)
        {
            var loaisp = objShopOnlineEntities.LoaiSanPhams.Where(n => n.MaLoaiSP == id).FirstOrDefault();
            return View(loaisp);
        }


        [HttpPost]
        public ActionResult Edit(string id, LoaiSanPham loaisp)
        {
            objShopOnlineEntities.Entry(loaisp).State = EntityState.Modified;
            objShopOnlineEntities.SaveChanges();
            return RedirectToAction("LoaiSP");
        }


        [HttpGet]
        public ActionResult Delete(string id)
        {
            var loaisp = objShopOnlineEntities.LoaiSanPhams.Where(n => n.MaLoaiSP == id).FirstOrDefault();
            return View(loaisp);
        }


        [HttpPost]
        public ActionResult Delete(string id, LoaiSanPham objDelete)
        {
            var loaisp = objShopOnlineEntities.LoaiSanPhams.Where(n => n.MaLoaiSP == id).FirstOrDefault();
            objShopOnlineEntities.LoaiSanPhams.Remove(loaisp);
            objShopOnlineEntities.SaveChanges();
            return RedirectToAction("LoaiSP");
        }

        public ActionResult Detais(string id)
        {
            var loaisp = objShopOnlineEntities.LoaiSanPhams.Where(n => n.MaLoaiSP == id).FirstOrDefault();
            return View(loaisp);
        }
    }
}

Controllers/ShopPageController.cs
using PagedList;
using ShopOnline.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopOnline.Controllers
{
    public class ShopPageController : Controller
    {
        ShopOnlineEntities objShopOnlineEntities = new ShopOnlineEntities();
        // GET: ShopPage
        public ActionResult ShopPage(int? page)
        {

            var lstSanPham = objShopOnlineEntities.SanPhams.ToList();
            int pageSize = 8;
            int pageNumber = (page ?? 1);
            return View(lstSanPham.ToPagedList(pageNumber, pageSize));
        }

        // GET: ShopPage/Details/5
        public ActionResult Details(string id)
        {
            var objProduct = objShopOnlineEntities.SanPhams.Where(n => n.MaSP == id).FirstOrDefault();

            return View(objProduct);
           
        }

        // GET: ShopPage/Create
        public ActionResult ProductSamSung(string id, int? page)
        {
            var lstProductSamSung = objShopOnlineEntities.SanPhams.Where(n => n.MaNSX == id).ToList();
            int pageSize = 8;
            int pageNumber = (page ?? 1);
            return View(lstProductSamSung.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult LoaiSP(string id, int? page)
        {
            var lstLoaiSP = objShopOnlineEntities.SanPhams.Where(n => n.MaLoaiSP == id).ToList();
            int pageSize = 4;
            int pageNumber = (page ?? 1);
            return View(lstLoaiSP.ToPagedList(pageNumber, pageSize));
        }

        // POST: ShopPage/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ShopPage/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ShopPage/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ShopPage/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ShopPage/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/ShopPage/LoaiSP.cshtml
@model PagedList.IPagedList<ShopOnline.Context.SanPham>
@using PagedList.Mvc;
@using PagedList;


@{
    ViewBag.Title = "LoaiSP";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="product-big-title-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="product-bit-title text-center">
                    <h2>Loại Sản Phẩm</h2>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="single-product-area">
    <div class="zigzag-bottom"></div>
    <div class="container">
        <div class="row">
            @foreach (var item in Model)

            {
                <div class="col-md-3 col-sm-6">
                    <div class="single-shop-product">
                        <div class="product-upper">
                            <a href="@Url.Action("Details", "ShopPage" ,new { id = item.MaSP })"><img style="width:195px;height:243px;" src="~/Asset/img/@item.HinhChinh"></a>
                        </div>
                        <h2><a href="@Url.Action("Details", "ShopPage" ,new { id = item.MaSP })"> @item.TenSP</a></h2>

                        <div class="product-carousel-price">
                            <h5 class="item_price">Price: @item.Gia.Value.ToString("#,##") VNĐ</h5>
                        </div>

                        <div class="product-option-shop">
                            <a class="add_to_cart_button" data-quantity="1" data-product_sku="" data-product_id="70" rel="nofollow" href="/canvas/shop/?add-to-cart=70">Add to cart</a>
                        </div>
                    </div>
                </div>
            }



        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="product-pagination text-center">
                    <nav>
                        <ul class="pagination">
                            @Html.PagedListPager(Model, page => Url.Action("LoaiSP", new { page }))

                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>

Views/ShopPage/ProductSamSung.cshtml
@model PagedList.IPagedList<ShopOnline.Context.SanPham>
@using PagedList.Mvc;
@using PagedList;

@{
    ViewBag.Title = "ProductSamSung";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="product-big-title-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="product-bit-title text-center">
                    <h2>Thương Hiệu</h2>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="single-product-area">
    <div class="zigzag-bottom"></div>
    <div class="container">
        <div class="row">
            @foreach (var item in Model)

            {
                <div class="col-md-3 col-sm-6">
                    <div class="single-shop-product">
                        <div class="product-upper">
                            <a href="@Url.Action("Details", "ShopPage" ,new { id = item.MaSP })"><img style="width:195px;height:243px;" src="~/Asset/img/@item.HinhChinh"></a>
                        </div>
                        <h2><a href="@Url.Action("Details", "ShopPage" ,new { id = item.MaSP })"> @item.TenSP</a></h2>

                        <div class="product-carousel-price">
                            <h5 class="item_price">Price: @item.Gia.Value.ToString("#,##") VNĐ</h5>
                        </div>

                        <div class="product-option-shop">
                            <a class="add_to_cart_button" data-quantity="1" data-product_sku="" data-product_id="70" rel="nofollow" href="/canvas/shop/?add-to-cart=70">Add to cart</a>
                        </div>
                    </div>
                </div>
            }



        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="product-pagination text-center">
                    <nav>
                        <ul class="pagination">
                            @Html.PagedListPager(Model, page => Url.Action("ProductSamSung", new { page }))

                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>

Views/ShopPage/ShopPage.cshtml
@using PagedList.Mvc;
@using PagedList;
@model PagedList.IPagedList<ShopOnline.Context.SanPham>



@{
    ViewBag.Title = "ShopPage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="product-big-title-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="product-bit-title text-center">
                    <h2>Shop</h2>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="single-product-area">
    <div class="zigzag-bottom"></div>
    <div class="container">
        <div class="row">
            @foreach (var item in Model)

            {
                <div class="col-md-3 col-sm-6">
                    <div class="single-shop-product">
                        <div class="product-upper">
                            <a href="@Url.Action("Details", "ShopPage" ,new { id = item.MaSP })"><img style="width:220px;height:269px;" src="~/Asset/img/@item.HinhChinh"></a>
                        </div>
                        <h2><a href="@Url.Action("Details", "ShopPage" ,new { id = item.MaSP })"> @item.TenSP</a></h2>

                        <div class="product-carousel-price">
                            <h5 class="item_price">Price: @item.Gia.Value.ToString("#,##") VNĐ</h5>
                        </div>

                        <div class="product-option-shop">
                            <a  href="@Url.Action("AddToCart","Cart", new { @id = item.MaSP, @strURL = Request.Url.ToString() })"  class="add_to_cart_button" data-quantity="1" data-product_sku="" data-product_id="70" rel="nofollow" >Thêm vào giỏ</a>
                        </div>
                    </div>
                </div>
            }



        </div>

        <div class="row">
            <div class="col-md-12">

                <div class="product-pagination text-center">
                    <nav>
                        <ul class="pagination">
                            @Html.PagedListPager(Model, page => Url.Action("ShopPage", new { page }))

                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>